name: Build Thesis

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      # FIXME ↓
      # - name: Cache texlive installation
      #   id: texlive-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: /home/runner/texlive # $HOME/texlive
      #     key: ${{ hashFiles('tex-packages.txt') }}

      - name: Install texlive
        run: |
          pip install https://github.com/maxnoe/texlive-batch-installation/archive/refs/tags/v0.3.0.tar.gz
          install_texlive -p $HOME/texlive -t 2021 --collections="-a" --package-file tex-packages.txt --update
          echo "$HOME/texlive/2021/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Build document
        run: |
          make

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: build/thesis.pdf

      - name: Extract PDFs for bundling
        run: mkdir gh-pages-bundle && rsync -a --prune-empty-dirs --include '*/' --include '*.pdf' --exclude '*' ./ gh-pages-bundle/

      - name: Generate index
        run: sudo apt-get install tree && cd gh-pages-bundle && tree -H . > index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: gh-pages-bundle

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v1
